baseURL = "https://anirbankopty.github.io/"
languageCode = 'en'
title = "Anirban Kopty"
theme = "coder"

[params]
author = "Anirban Kopty"
description = "Anirban Kopty's personal website"
info = ["Research Scholar", "IUCAA, India"]
avatarURL = ""
# gravatar = "anirban.kopty@example.com"
colorScheme = 'auto'
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":in:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts"


[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/anirbankopty/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 1
url = "https://gitlab.com/anirbankopty/"
